export { base } from "./src/base";
export { layerBase } from "./src/layerBase";
export { chartBase } from "./src/chartBase";
export { axesChart } from "./src/axesChart";
export { scatter } from "./src/scatter";
export { xLine, yLine, parametricCurve } from "./src/lines";
export { heatmap } from "./src/heatmap";
export { cache, separateBy, getEuclideanDistance, add_click_listener, pearsonCorr, fillTextBlock, get_symbolSize, escapeRegExp } from "./src/additionalFunctions";
export { colourSlider } from "./src/colourSlider";
export { table } from "./src/table";
export { barchart } from "./src/barchart";
export { dendogram } from "./src/dendogram";
export { beeswarm } from "./src/beeswarm";
