export { base } from "./src/base";
export { layerBase } from "./src/layerBase";
export { layerChart } from "./src/layerChart";
export { chartBase } from "./src/chartBase";
export { axesChart } from "./src/axesChart";
export { scatter } from "./src/scatter";
export { xLine, yLine, parametricCurve, pointLine, pointRibbon } from "./src/lines";
export { heatmap } from "./src/heatmap";
export { cache, separateBy, getEuclideanDistance, add_click_listener, pearsonCorr, get_symbolSize, escapeRegExp, check, call_pacer, isNaN, random } from "./src/additionalFunctions";
export { colourSlider } from "./src/colourSlider";
export { table, html, input, image } from "./src/table";
export { barchart } from "./src/barchart";
export { dendogram } from "./src/dendogram";
export { beeswarm } from "./src/beeswarm";
